/* Generated by Babel */
'use strict';

var login = function login(username, password) {
  if (username !== 'admin' || password !== 'password') {
    console.log('incorrect login');
  }
};

login('admin', 'false');